root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -v -buildvcs=false -o ./golang-demo ."
  bin = "./golang-demo"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "terraform"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  follow_symlink = false
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false