# Start from the official Golang image
FROM golang:1.23.1

# Set the working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN GOOS=linux GOARCH=amd64 go build -o golang-demo

# Command to run the executable
CMD ["./golang-demo"]