# templates/db-init-job.yaml
{{- if .Values.dbInit.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15
        command: ['/bin/bash', '-c']
        args:
          - PGPASSWORD="$DB_PASSWORD" psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "CREATE TABLE IF NOT EXISTS videos (id VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL);"
        env:
          - name: DB_HOST
            value: {{ .Values.config.database.external.host }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-credentials
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-credentials
                key: database
      restartPolicy: Never
  backoffLimit: 4
{{- end }}