apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-golang-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-demo
  template:
    metadata:
      labels:
        app: golang-demo
    spec:
      containers:
        - name: golang-demo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Database configuration
            {{- if eq .Values.config.environment "local" }}
            - name: DB_ENDPOINT
              value: {{ .Release.Name }}-postgres
            {{- else }}
            - name: DB_ENDPOINT
              value: {{ .Values.config.database.external.host }}
            {{- end }}
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: database
          ports:
            - containerPort: 8080