{{- if and (eq .Values.config.environment "local") (eq .Values.config.database.local.enabled true) .Values.config.database.local.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config.database.local.persistence.size }}
{{- end }}