{{- if and (eq .Values.config.environment "local") (eq .Values.config.database.local.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
{{- end }}