apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
type: Opaque
data:
  {{- if eq .Values.config.environment "local" }}
  username: {{ .Values.config.database.local.credentials.username | b64enc }}
  password: {{ .Values.config.database.local.credentials.password | b64enc }}
  database: {{ .Values.config.database.local.credentials.database | b64enc }}
  {{- else }}
  username: {{ .Values.config.database.external.credentials.username | b64enc }}
  password: {{ .Values.config.database.external.credentials.password | b64enc }}
  database: {{ .Values.config.database.external.credentials.database | b64enc }}
  {{- end }}