apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-golang-demo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: golang-demo
